---
- hosts: all
  gather_facts: False
  sudo: yes
  
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


# install anaconda and start jupyter server on instance with tags class=database
- hosts: tag_class_jupyter  
  sudo: no  
  
  roles:  
    - jupyter  
     

