---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    region: us-west-1   
  tasks:  
    - name: launch instance
      ec2:
        region: "{{ region }}"  
        key_name: tgkey1  
        instance_type: c4.xlarge  
        image: ami-6e165d0e
        wait: yes    
        group: sg_jupserver_uswest
        instance_tags:  
          Name: jupyter-1  
          class: jupyter-server   
      register: ec2  
    - name: associate new EIP for the instance    
      ec2_eip:
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
      with_items: ec2.instances
