---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    #your region  
    region: us-west-1  
    #your ip address
    allowed_ip: 0.0.0.0/0
  tasks:  
    - name: create security group  
      ec2_group:
        region: "{{ region }}"
        name: sg_jupserver_uswest    
        description: security group for uswest jupyter server host
        rules:
          # allow ssh access from your ip address  
          - proto: tcp  
            from_port: 22  
            to_port: 22  
            cidr_ip: "{{ allowed_ip }}"  
          # allow https access from anywhere  
          - proto: tcp  
            from_port: 8888    
            to_port: 8888    
            cidr_ip: 0.0.0.0/0  
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
